//
//  AuxBank.swift
//  BoatSchool
//
//  Created by Zach Venanzi on 3/29/21.
//

import Foundation

struct Contents {
    static var subjects = ["General Subjects","Refrigeration","Safety","Gas Turbines","Steam Plants","Motor Plants","Electricity","Electronics and Control Engineering"]
    static var generalSubjectsSubs = [
        "Blueprints",
        "Drawing",
        "Piping",
        "Piping Symbols and Systems",
        "Pipe Fittings",
        "Tubing",
        "Conversion Factors",
        "Screwdrivers",
        "Files",
        "Chisels",
        "Saws",
        "Drills",
        "Taps and Dies",
        "Screw Threads and Fasteners",
        "Miscellaneous Tools",
        "Measuring Tools (Shop)",
        "Lathe Operations",
        "Heat Treatment",
        "Non-Destructive Testing",
        "Soldering",
        "Welding",
        "Packing and Gaskets",
        "Mechanical Seals",
        "Valves",
        "Power Operated Valves",
        "Taps, Drains, and Strainers",
        "Centrifugal Pump Design",
        "Centrifugal Pump Operation",
        "Reciprocating Pumps",
        "Reciprocating Pump Problems",
        "Rotary Pumps",
        "Jet Pumps",
        "Miscellaneous Pumps",
        "Air Compressors",
        "Air Compressor Trouble Shooting",
        "Heat Exchangers",
        "Steam Systems",
        "Fresh Water Drains",
        "Contaminated Drains",
        "Bilge and Ballast Systems",
        "Oily Water Separator",
        "Sanitary and Sewage Systems",
        "Potable Water Systems",
        "Saltwater Systems",
        "Condensers",
        "Air Ejectors",
        "Feed Heaters",
        "D.C. Heaters",
        "Feed Pumps",
        "Feed Water Systems",
        "Flash Evaporators",
        "Submerged Tube Evaporators",
        "Miscellaneous Evaporators",
        "Evaporator Salinity",
        "Evaporators, Special",
        "Hydraulic Systems",
        "Hydraulic Flow Control Devices",
        "Hydraulic System Components",
        "Hydraulic Hose and Piping",
        "Hydraulic Accumulators",
        "Hydraulic Pumps, Motors, Rams",
        "Hydraulic Fluid",
        "Hydraulic System Operation",
        "Steering Gear",
        "Steering Gear Control Devices",
        "Steering Gear Operation",
        "Steering Gear Regs",
        "Propellers",
        "Controllable Pitch Propellers",
        "Propulsors, Thrusters",
        "Incinerators",
        "Deck Machinery",
        "Ball and Roller Bearings",
        "Grease",
        "Corrosion, Cathodic Protection",
        "Ship Construction",
        "Oil Tanks",
        "Tank Cleaning",
        "Oil Tank Vents",
        "Oil Transfer Operations",
        "Fuel and Cargo Hoses",
        "Inert Gas",
        "LNG",
        "Supply Boat Operations",
        "International Regulations",
        "Maintneance Management",
        "Watchstanding, Machinery Operation",
        "Vessel Security",
        "Training",
        "Leadership, Managment, ERM",
        "Calculations"]
}


